Thread race
Resci/multithreading pull request #1
Opened 2021-02-23 11:12 UTC by Resci

2021-02-23 11:51 UTC, oleksandrdziubiuk approved these changes

2021-02-23 14:31 UTC, RomanDubovskyi requested changes

2021-02-23 14:31 UTC, RomanDubovskyi commented on src/main/java/com/mate/App.java
> +        MyThread myThread = new MyThread(counter, INCREMENT_TO);
```suggestion
        Thread myThread = new MyThread(counter, INCREMENT_TO);
```
we should always use more abstract type if it's possible

2021-02-23 14:31 UTC, RomanDubovskyi commented on src/main/java/com/mate/Counter.java
> +        count = count + 1;
```suggestion
        count++;
```

2021-02-23 15:12 UTC, RomanDubovskyi approved these changes

2021-02-23 15:14 UTC, merged

2021-02-24 00:13 UTC, tonitrus55 commented on src/main/java/com/mate/Counter.java
> +    public void increment() {
count++

2021-02-24 00:13 UTC, tonitrus55 commented on src/main/java/com/mate/Counter.java
> +        count = 0;
При создании объекта - у тебя count всегда будет 0